spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/Cherries
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fairyberry
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true