spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:~/testdb    # Use in-memory H2 database for development or testing
    driver-class-name: org.h2.Driver
    username: sa               # Default H2 username
    password: password         # Default H2 password
  jpa:
    hibernate:
      ddl-auto: update         # Automatically update the schema
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.H2Dialect
        format_sql: true        # Format the SQL logs for readability
    show-sql: true              # Show SQL queries in logs